#!/usr/bin/env bash

set -e

main() {
  echo "TODO: private apps"
  echo "TODO: preferences"
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/osx"

  nodenv rehash
  rbenv rehash

  build-locate-database

  backup-weird-bundle
  install-shellcheck
  # remove-karabiner-startup
}

build-locate-database() {
  # To make locate work
  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
}

backup-weird-bundle() {
  mv -f /usr/local/bin/bundle{,.backup} | true
}

install-shellcheck() {
  if ! which shellcheck > /dev/null 2>&1; then
    cabal update
    cabal install shellcheck
  fi
}

remove-karabiner-startup() {
  karabiner_launch="/Library/LaunchDaemons/org.pqrs.Karabiner.load.plist"
  sudo rm "$karabiner_launch" | true
}
main "$@"
