#!/usr/bin/env bash

set -e

main() {
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/install-private-apps"
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/link-cloud-configs"
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/osx"

  nodenv rehash
  rbenv rehash

  backup-weird-bundle
  install-shellcheck
}

backup-weird-bundle() {
  mv -f /usr/local/bin/bundle{,.backup} | true
}

install-shellcheck() {
  if ! which shellcheck 2>&1 > /dev/null; then
    cabal update
    cabal install shellcheck
  fi
}
main "$@"
