#!/usr/bin/env bash

set -e

main() {
  path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "$path/install-private-apps"
  source "$path/link-cloud-configs"
  source "$path/osx"
}

main "$@"
