#!/usr/bin/env bash

set -e

main() {
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/install-private-apps"
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/link-cloud-configs"
  source "$DOTFILES_PATH/configuration/scripts/after-boxen.d/osx"

  nodenv rehash
  rbenv rehash

  build-locate-database

  backup-weird-bundle
  install-shellcheck
}

build-locate-database() {
  # To make locate work
  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
}

backup-weird-bundle() {
  mv -f /usr/local/bin/bundle{,.backup} | true
}

install-shellcheck() {
  if ! which shellcheck > /dev/null 2>&1; then
    cabal update
    cabal install shellcheck
  fi
}
main "$@"
