#!/usr/bin/env bash

set -e

main() {
  install-xcode
  use-sudo
  install-boxen
}

use-sudo() {
  sudo -v
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

install-xcode() {
  xcode-select --install 2>/dev/null | true
}

install-boxen() {
  if [ ! -d /opt/boxen ]
  then
    BOXEN_PATH=/opt/boxen
    sudo mkdir -p $BOXEN_PATH
    sudo chown ${USER}:staff $BOXEN_PATH
    git clone https://github.com/boxen/our-boxen.git $BOXEN_PATH/repo
    cd $BOXEN_PATH/repo
    sudo chown -R ${USER}:admin $BOXEN_PATH
    ./script/boxen
  fi
}
main "$@"
