#!/usr/bin/env ruby
require 'fileutils'
require 'erb'
require 'ostruct'

require './lib/dotfiles_processor'
require './lib/dotfiles_installer'
require './lib/karabiner_configurer'
require './lib/pomodoremi_installer'

Dir.chdir File.dirname(File.expand_path(__FILE__))
Dir.chdir('../..')
DotfilesInstaller.exec
KarabinerConfigurer.exec
PomodoremiInstaller.exec
