#!/usr/bin/env bash

set -e

main() {
  echo 'Link cloud configs'
  if [ "$1" == '-f' ]
  then
    force='true'
  else
    force='false'
  fi

  donefiles="$HOME/main/support/temp/misc/link_cloud_configs"
  personal_src="$HOME/main/support/cloud_storage/docs/config/personal_preferences"
  personal_dest="$HOME/Library/Preferences"

  general_src="$HOME/main/support/cloud_storage/docs/config/general_preferences"
  general_dest="/Library/Preferences"

  if [ $force == 'true' ]
  then
    rm -rf $donefiles/*
  fi

  process_dir $personal_src $personal_dest "$donefiles/personal"
  process_dir $general_src $general_dest "$donefiles/general"
}
process_dir() {
  src=$1
  dest=$2
  donefiles=$3
  if [ ! -e $src ]; then exit 1; fi

  mkdir -p $donefiles

  for file in "$src/*"
  do
    name=$(basename $file)
    process $name $src $dest $donefiles
  done
}

process() {
  name=$1
  src=$2
  dest=$3
  donefiles=$4

  if [ -e "$donefiles/$name" ]
  then
    echo [Skip] $dest/$name
    continue
  fi

  cp "$src/$name" "$dest/$name"
  touch "$donefiles/$name"
  echo [Done] $dest/$name
}

main "$@"
