#!/usr/bin/env bash

set -e

main() {
  path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "$path/install_private_apps"
  source "$path/link_cloud_configs"
  source "$path/osx"
}

main "$@"
