#!/usr/bin/env bash

set -e

main() {
  echo "Configuring OSX"
  if(first-run); then
    preferences-manager restore || true
  fi

  set-up-mathiasbynens-dot-macos || true
  set-up-my-config
}

set-up-mathiasbynens-dot-macos() {
  URL="https://raw.githubusercontent.com/mathiasbynens/dotfiles/master/.macos"
  FILE="$(mktemp "$TMPDIR".macos.XXXXXXXXXX)"
  [ -e "$SCRIPT_PATH" ] ||  (curl "$URL" > "$FILE" &&
      chmod +x "$FILE" &&
      "$FILE")
}

set-up-my-config() {
  # Normal scrolling direction
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
  # Reenable notifications
  launchctl load -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist || true

  # Dark mode
  dark-mode on

  # Black background
  # set-black-wallpaper

  # Hide all icons from desktop
  defaults write com.apple.finder CreateDesktop -bool false

  # Disable two hot corners
  defaults write com.apple.dock wvous-tr-corner -int 0
  defaults write com.apple.dock wvous-bl-corner -int 0

  # Disable screensaver
  defaults write com.apple.screensaver idleTime 0

  # Set timezone
  sudo systemsetup -settimezone "GMT" > /dev/null

  set-up-finder

  killall Finder
}

set-up-finder() {
  defaults write com.apple.finder ShowStatusBar -bool false
  defaults write com.apple.finder ShowPathbar -bool false

  defaults write com.apple.finder NewWindowTarget -string "PfLo"
  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/main/"
}

set-black-wallpaper() {
  # This doesn't work for all spaces well
  # Also should notify that it will start setting wallpaper
  if [ ! "$(wallpaper)" = "$HOME/.wallpaper.png" ]; then
    generate-image black "$HOME/.wallpaper.png"
    osx-app-spaces-manager --each-space="wallpaper '$HOME/.wallpaper.png'"
  fi
}

generate-image() {
  convert -size 100x100 xc:"$1" "$2"
}

first-run() {
  if [ -e "$HOME/.config/welldan97/.configuration-installed-osx" ]; then
    return 1
  else
    mkdir -p "$HOME/.config/welldan97/"
    echo "This file verifies configuration installed" > "$HOME/.config/welldan97/.configuration-installed-osx"
    return 0
  fi
}

main "$@"
