#!/usr/bin/env bash

set -e

main() {
  echo "Configuring OSX"

  set-up-mathiasbynens-dot-macos
  set-up-my-config
}

set-up-mathiasbynens-dot-macos() {
  URL="https://raw.githubusercontent.com/mathiasbynens/dotfiles/master/.macos"
  SCRIPT_PATH="$HOME/.macos"
  [ -e "$SCRIPT_PATH" ] ||  (curl "$URL" > "$SCRIPT_PATH" &&
      chmod +x "$SCRIPT_PATH" &&
      "$SCRIPT_PATH")
}

set-up-my-config() {
  # Normal scrolling direction
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
  # Reenable notifications
  launchctl load -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist || true

  # Dark mode
  dark-mode --mode Dark

  # Black background
  set-black-wallpaper

  # Light blue highlight (like in Iterm)
  defaults write NSGlobalDomain AppleHighlightColor -string "0.71 0.84 1"

  # Hide all icons from desktop
  defaults write com.apple.finder CreateDesktop -bool false

  # Disable two hot corners
  defaults write com.apple.dock wvous-tr-corner -int 0
  defaults write com.apple.dock wvous-bl-corner -int 0

  # Disable screensaver
  defaults write com.apple.screensaver idleTime 0

  set-up-finder

  killall Finder
}

set-up-finder() {
  defaults write com.apple.finder ShowStatusBar -bool false
  defaults write com.apple.finder ShowPathbar -bool false

  defaults write com.apple.finder NewWindowTarget -string "PfLo"
  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/main/"
}

set-black-wallpaper() {
  if [ ! "$(wallpaper)" = "$HOME/.wallpaper.png" ]; then
    generate-image black "$HOME/.wallpaper.png"
    osx-app-spaces-manager --each-space="wallpaper '$HOME/.wallpaper.png'"
  fi
}

generate-image() {
  convert -size 100x100 xc:"$1" "$2"
}

main "$@"
