#!/usr/bin/env bash

set -e

RUBY_VERSIONS=(2.4.1)

main() {
  install-ruby-versions
  install-ruby-gems
}

ls-ruby-gems() {
  echo bundler
  echo churn
  echo pry
  echo pry-remote
  echo rubocop
  echo scss_lint
  echo scss_lint_reporter_checkstyle
  echo trello_cli
}

install-ruby-versions() {
  for version in ${RUBY_VERSIONS[@]}; do
    is-version-already-installed "$version" || rbenv install "$version"
  done
  rbenv global ${RUBY_VERSIONS[0]}
}

install-ruby-gems() {
  for gem in $(ls-ruby-gems); do
    echo "Installing $gem"
    is-already-installed "$gem" ||
      gem install "$gem"
  done
}

is-already-installed() {
  installed-ruby-gems | grep -q "^$1\$"
}

is-version-already-installed() {
  rbenv global | grep -q "^$1\$"
}

installed-ruby-gems() {
  for gem in ${INSTALLED_GEMS[@]}; do
    echo $gem
  done
}

unmemoized-installed-ruby-gems() {
  gem list | sed 's/ .*//'
}

INSTALLED_GEMS=($(unmemoized-installed-ruby-gems))


main "$@"
