#!/bin/bash

# Info
# ==============================================================================

# To use run the following line in your terminal
# bash <(curl -fs https://raw.githubusercontent.com/welldan97/dotfiles/master/battlecruiser) -c ./config.json

# battlecruiser
# battlecruiser setup
# battlecruiser setup git
# battlecruiser setup -hds
# battlecruiser setup git -hds

# Initialization
# ==============================================================================

set -eEo pipefail

DEFAULT_PATH="$HOME/.config/battlecruiser"
DEFAULT_REPO="https://github.com/welldan97/dotfiles.git"

FINAL_PATH="${BATTLECRUISER_PATH:-$DEFAULT_PATH}"
FINAL_REPO="${BATTLECRUISER_REPO:-$DEFAULT_REPO}"

# NOTE: may be use proper codes later on
ERROR_CODE=1

# levels
# 3 - annotate each step
# 2 - times & debug info
# 1 - open blocks
# 0 - only base info
LOG_LEVEL=1

trap "throw_error 'Oops! Something went wrong'" ERR

# Utils (used in other scripts as well)
# ==============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
GRAY='\033[0;37m'
NC='\033[0m'

throw_error() {
  # shellcheck disable=SC2059
  printf "\n${RED}ERROR: %s${NC}\n" "$1"
  exit "$ERROR_CODE"
}

print_title() {
  printf "\n🚢  %s\n\n" "$1"
}

print_end() {
  # shellcheck disable=SC2059
  printf "\n🚢  ${GREEN}Battlecruiser Operational${NC}\n\n"
}

((subtitle_seconds=0))
((subtitle_index=1))
print_subtitle() {
  if [[ "$1" == "--success" ]]; then
    printf "\n  ✅  %s. %s\n" "$subtitle_index" "$2"
    if ((SECONDS - check_seconds > 3 )) ;then
      printf "  ${RED}%s sec${NC}\n" "$(( SECONDS - subtitle_seconds ))"
    elif (( LOG_LEVEL >= 2 )) ;then
      printf "  ${GRAY}%s sec${NC}\n" "$(( SECONDS - subtitle_seconds ))"
    fi

    printf "\n"
    ((subtitle_index=subtitle_index+1))
  else
    printf "\n  📢  %s. %s\n  ${GRAY}%s${NC}\n" "$subtitle_index"  "$1" "$2"
    ((subtitle_seconds=SECONDS))
  fi
  echo "$subtitle_seconds" > /dev/null
}

((check_seconds=0))
print_check() {
  ((check_seconds=SECONDS))
  printf "    ⚓️  %s" "$1"
}

print_hr() {
  # shellcheck disable=SC2059
  printf "${GRAY}"
  printf "~%.0s" {1..80}
  # shellcheck disable=SC2059
  printf "${NC}"
  printf "\n"
}

print_block_start() {
  printf '\n'
  print_hr
  # shellcheck disable=SC2059
  printf "${GRAY}"
}

print_block_end() {
  # shellcheck disable=SC2059
  printf "${NC}"
  print_success_short
  print_hr
}


print_success() {
  printf "  -  ✅ "
  if [[ "$#" != "0" ]] ;then
     printf " ${GREEN}%s${NC}" "$1"
  fi

  if ((SECONDS - check_seconds > 3 )) ;then
    printf " ${RED}%s sec${NC}" "$(( SECONDS - check_seconds ))"
  elif (( LOG_LEVEL >= 2 )) ;then
    printf " ${GRAY}%s sec${NC}" "$(( SECONDS - check_seconds ))"
  fi

  printf "\n"
}

print_success_short() {
  color="$GRAY"
  if [[ "$((SECONDS - check_seconds ))" -gt 10 ]]; then
    color="$RED"
  fi

  # shellcheck disable=SC2059
  (( LOG_LEVEL >= 2 )) && printf "  ✅  ${GREEN}Done${NC} ${color}%s sec${NC}\n" "$(( SECONDS - check_seconds ))" || true
  (( LOG_LEVEL < 2 )) && printf "  ✅  ${GREEN}Done${NC}\n" || true
}

set_status() {
  echo "$1" > "$FINAL_PATH/status"
}

get_status() {
  cat "$FINAL_PATH/status" || echo 'none'
}

confirm() {
  while true; do
    printf -- '- '
    read -r answer
    if [ "$answer" = 'yes' ]; then
      return 0
    elif [ "$answer" = 'no' ]; then
      return 1
    else
      printf '\n- Please, answer yes or no.\n\n'
    fi
  done
}


# Initialization
# ==============================================================================

initialize() {
  print_subtitle "Initialization"

  ensure_is_admin
  ensure_path_exists
  maybe_move_config "$@"
  ensure_config_exists
  ensure_repository_exists
  ensure_repository_is_up_to_date
  ensure_executable

  if [[ "$(get_status)" == "initializing" ]]; then
    set_status "installing"
  fi

  print_subtitle --success "Initialization"
}

is_admin() {
  id -G "$USER" 2> /dev/null |
    grep -q -w 80
}

ensure_is_admin() {
  print_check "Must be admin"
  if is_admin; then
    print_block_start

    sudo -v

    # Keep-alive: update existing `sudo` time stamp until finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    print_block_end
  else
    throw_error "Must be admin"
  fi
}

ensure_path_exists() {
  print_check "Home path exists"
  if [[ -d "$FINAL_PATH" ]]; then
    print_success
  else
    print_block_start

    printf "Initializing Battlecruiser home dir in \"%s\"\n" \
      "$FINAL_PATH"
    mkdir -p "$FINAL_PATH"
    set_status "initializing"

    print_block_end
  fi
}

maybe_move_config() {
  print_check "Config provided as an argument"

  is_config='false'
  while (( "$#" )); do
    case "$1" in
      -c|--config)
        print_block_start
        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
          is_config='true'
          printf "Config is provided. Moving it from \"%s\" to \"%s\"\n\n" \
            "$2" "$FINAL_PATH/config.json"
          mv "$2" "$FINAL_PATH/config.json"
          shift 2
        else
          throw_error "Argument for $1 is missing"
        fi
        print_block_end
        ;;
      *)
        shift
        ;;
    esac
  done

  if [[ "$is_config" == 'false' ]]; then
    print_success 'It is not'
  fi
}

ensure_config_exists() {
  print_check "Config exists"
  if [[ -f "$FINAL_PATH/config.json" ]]; then
    print_success
  else
    throw_error "Config is not found at \"$FINAL_PATH/config\""
  fi
}


ensure_repository_exists() {
  print_check "Repository exists"
  if [[ -d "$FINAL_PATH/repository" ]]; then
    print_success
  else
    print_block_start

    printf "Cloning repository from \"%s\" to \"%s\" \n\n" \
      "$FINAL_REPO" "$FINAL_PATH/repository"
    git clone "$FINAL_REPO" "$FINAL_PATH/repository"

    print_block_end
  fi
}

repository_is_behind() {
  (
    cd "$FINAL_PATH/repository" &&
      git remote update > /dev/null &&
      git status -uno | grep -q 'branch is behind'
  )

  return "$?"
}

ensure_repository_is_up_to_date() {
  print_check "Repository is up to date"
  if ! repository_is_behind; then
    print_success
  else
    print_block_start

    (
      cd "$FINAL_PATH/repository" &&  git pull origin master
    )

    print_block_end
  fi
}

ensure_executable() {
  print_check "Executable exists in PATH"
  if command -v battlecruiser > /dev/null 2>&1; then
    print_success
  else
    if [[ -f "$FINAL_PATH/bin/battlecruiser" ]]; then
      print_success "Command is not found, but it's in your PATH"
    else
      print_block_start

      printf "Adding \"battlecruiser\" to your \$PATH in \"%s/.bashrc\"\n" \
        "$HOME"
      printf "Adding \"battlecruiser\" to your \$PATH in \"%s/.zshrc\"\n" \
        "$HOME"
      mkdir -p "$FINAL_PATH/bin"
      ln -s "$FINAL_PATH/repository/battlecruiser" "$FINAL_PATH/bin/battlecruiser"
      printf "\nexport PATH=\"\$PATH:%s/bin\"\n" "$FINAL_PATH" \
        >> "$HOME/.bashrc"
      printf "\nexport PATH=\"\$PATH:%s/bin\"\n" "$FINAL_PATH" \
        >> "$HOME/.zshrc"

      print_block_end
    fi
  fi
}

# Main
# ==============================================================================

main() {
  if [[ "$#" == "0" ]]; then # no arguments
    battlecruiser_setup
    return;
  fi

  if [[ "$1" == "--help" ]]; then
    help
    return;
  fi

  if [[ "$1" == "--version" ]]; then
    version
    return;
  fi

  if [[ "$1" == -* ]]; then # no command, just options
    battlecruiser_setup "$@"
  else
    case "$1" in
      help)
        help
        ;;

      setup)
        shift
        if [[ "$1" == "--version" ]]; then
          version
          return;
        fi
        if [[ "$1" == "--help" ]]; then
          setup_help
          return;
        fi
        battlecruiser_setup "$@"
        ;;

      *)
        throw_error "unknown command or file \"$1\""
        ;;
    esac
  fi
}

# Commands
# ==============================================================================

help() {
  cat << EOF

    Usage
      $ battlecruiser <command>

    Available commands
      setup(default), help

    Options
      --version       Show Version
      --help          Displays this message
      --config        Supply path to config json

    Example:
      battlecruiser --config config.json  -  bootstrap the system with
                                             config supplied


    For more information run a command with the --help flag
      $ battlecruiser setup --help

EOF
}

setup_help() {
  cat << EOF
    Description
      Setting up the system

    Usage:
      $ battlecruiser setup

    Options
      --include-steps
      --exclude-steps
      --include-bundles
      --exclude-bundles

EOF
}



version() {
  echo 0.9.0
}

battlecruiser_setup() {
  print_title "Set Up"
  initialize "$@"
  # shellcheck disable=SC1090
  source "$FINAL_PATH/repository/battlecruiser.d/setup"
  bc_setup "$@"
  print_end
}

main "$@"
