#!/usr/bin/env bash

set -e
#set -x

DOTFILES_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

main() {
  if [ -z $BOXEN_HOME ]; then echo 'Please provide $BOXEN_HOME';exit 1; fi

  before-config
  boxen
  after-config
}

before-config() {
  source "$DOTFILES_PATH/configuration/scripts/before"
}

boxen() {
  source "$DOTFILES_PATH/configuration/scripts/boxen"
}

after-config() {
  source "$DOTFILES_PATH/configuration/scripts/after"
}

main
