#!/usr/bin/env ruby
require 'fileutils'
require 'erb'
require 'ostruct'

require './lib/dotfiles_processor'
require './lib/dotfiles_installer'
require './lib/karabiner_configurer'

DotfilesInstaller.exec
KarabinerConfigurer.exec
