#!/usr/bin/env bash

set -e
#set -x

DOTFILES_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

main() {
  if [ -z $BOXEN_HOME ]; then echo 'Please provide $BOXEN_HOME';exit 1; fi

  sudo -v

  clean-boxen
  update-boxen
  sync-boxen
  run-boxen

  post-config
}

update-boxen() {
  cd $BOXEN_HOME/repo
  git pull
}

clean-boxen() {
  cd $BOXEN_HOME/repo
  git reset --hard
  git clean -d -f
  git checkout master
  git branch -d dev || true
}

sync-boxen() {
  cd $BOXEN_HOME/repo
  git checkout -b dev
  rsync -av "$DOTFILES_PATH/configuration/boxen/" "$BOXEN_HOME/repo/"
}

run-boxen() {
  cd $BOXEN_HOME/repo
  $BOXEN_HOME/repo/script/boxen &
  wait
}

post-config() {
  source "$DOTFILES_PATH/configuration/scripts/main"
}

main
