(defun singularize-or-pluralize-string (str)
  (let* ((result (singularize-string str)) )
    (if (eq result str) (pluralize-string str) (singularize-string str))))

(defun singularize-or-pluralize ()
  (interactive)
  (let* ((case-fold-search nil)
         (beg (and (skip-chars-backward "[:alnum:]:_-") (point)))
         (end (and (skip-chars-forward  "[:alnum:]:_-") (point)))
         (txt (buffer-substring beg end))
         (cml (singularize-or-pluralize-string txt)) )
    (if cml (progn (delete-region beg end) (insert cml)))))
