#!/usr/bin/env bash

updater-osx-software-name() {
  echo 'OSX Software'
}

updater-osx-software-detect() {
  which softwareupdate > /dev/null
}

updater-osx-software-update() {
  sudo softwareupdate -i --all
}

updater-osx-software-list() {
  if [ "$1" == '--no-fetch' ]; then
    software_update_output=$(sudo softwareupdate --list --no-scan 2>&1)
  else
    software_update_output=$(sudo softwareupdate --list 2>&1)
  fi

  if ! echo "$software_update_output" | grep -q 'No new software available.'; then
    echo "$software_update_output" | grep '\*' | sed -e 's/^[ 	]*\* //'
  fi
}
