#!/usr/bin/env bash

EMACS_PATH="$HOME/.emacs.d"

updater-emacs-prelude-name() {
  echo 'Emacs Prelude'
}

updater-emacs-prelude-detect() {
  [ -e "$EMACS_PATH/prelude-modules.el" ]
}

updater-emacs-prelude-update() {
  echo 'Not Implemented'
  #/Applications/Emacs.app/Contents/MacOS/Emacs --eval '(prelude-update)'
}


updater-emacs-prelude-list() {
  cd "$EMACS_PATH"
  if [ "$(updater-emacs-prelude-git-incomming | wc -l)" -gt 0 ]; then
    echo true
  else
    echo false
  fi
}

updater-emacs-prelude-git-incomming() {
  git fetch > /dev/null 2>&1 && git log ..origin/master
}
