#!/usr/bin/env bash

OH_MY_ZSH_PATH="$HOME/.oh-my-zsh/"

updater-oh-my-zsh-name() {
  echo 'Oh My ZSH'
}

updater-oh-my-zsh-detect() {
  [ -d "$OH_MY_ZSH_PATH" ]
}

updater-oh-my-zsh-update() {
  env ZSH="$OH_MY_ZSH_PATH" "/bin/sh $OH_MY_ZSH_PATH/tools/upgrade.sh"
}

updater-oh-my-zsh-list() {
  cd "$OH_MY_ZSH_PATH" || exit

  if [ "$(updater-oh-my-zsh-git-incomming | wc -l)" -gt 0 ]; then
    echo true
  else
    echo false
  fi
}

updater-oh-my-zsh-count() {
  updater-oh-my-zsh-list "$1" | wc -l | sed -e 's/^[ \t]*//'
}

updater-oh-my-zsh-git-incomming() {
  git fetch > /dev/null 2>&1 && git log ..origin/master
}
