#!/bin/bash

# Main
# ==============================================================================

bc_s_step_before() {
  if [[ ! -f "$BUNDLES_PATH/$1/before" ]]; then return; fi
  # shellcheck disable=SC1090
  source "$BUNDLES_PATH/$1/before"
}
