#!/bin/bash

# Utils
# ==============================================================================

_bc_s_step_dotfiles_render_template() {
  envsubst < "$1"
}

_bc_s_step_dotfiles_build_one_dotfile() {
  path="${1#"$BUNDLES_PATH/$2/dotfiles/"}"
  final_path="${path%'.bctemplate'}"

  (( LOG_LEVEL >= 1 )) && printf "processing %s\n" "$final_path" || true

  mkdir -p  "$(dirname "$BUILD_PATH/next/$final_path")"

  if echo "$1" | grep -q '\.bctemplate$'; then
    _bc_s_step_dotfiles_render_template "$1" > "$BUILD_PATH/next/$final_path"
  else
    cp "$1" "$BUILD_PATH/next/$final_path"
  fi
}

# Main
# ==============================================================================

bc_s_step_dotfiles() {
  if [[ ! -d "$BUNDLES_PATH/$1/dotfiles" ]]; then return; fi

  print_check "Installing dotfiles"
  (( LOG_LEVEL >= 1 )) && print_block_start || true

  find "$BUNDLES_PATH/$1/dotfiles" -type f  | while read -r line ; do
    _bc_s_step_dotfiles_build_one_dotfile "$line" "$1"
  done

  (( LOG_LEVEL >= 1 )) && print_block_end || true
  (( LOG_LEVEL < 1 )) && print_success || true
}
