#!/usr/bin/env bash

set -e

main() {
  case "$1" in
    restore)
      restore
      ;;
    *)
      backup
      ;;
  esac
}

backup() {
  echo Backing up...
  rclone sync -v --filter-from "$HOME/.rclone_products_filter" \
    "$HOME/main/products" \
    backblaze_b2:w97-backup/products
}

restore() {
  echo Restoring...
  rclone sync -v --filter-from "$HOME/.rclone_products_filter" \
    backblaze_b2:w97-backup/products \
    "$HOME/main/products"

}
main "$@"
