#!/usr/bin/env bash

set -e

# shellcheck disable=SC1090

main() {
  if [ -z "$DOTFILES_PATH" ]; then
    echo 'Please provide DOTFILES_PATH'
    exit 1
  fi

  use-sudo

  commands=(brew node ruby dotfiles general osx)
  if includes "$@" "${commands[@]}"; then
    source "$DOTFILES_PATH/configuration/scripts/$*"
  elif [[ "$*" == "all" ]]; then
    for command in "${commands[@]}"; do
      source "$DOTFILES_PATH/configuration/scripts/$command"
    done
  else
    echo 'Unknown command'
  fi
}

# Helpers

includes () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

use-sudo() {
  sudo -v
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

main "$@"
