#!/usr/bin/env bash

main() {
  while true; do
    read -r answer
    if [ "$answer" = 'yes' ]; then
      exit 0
    elif [ "$answer" = 'no' ]; then
      exit 1
    else
      echo 'Please answer yes or no'
    fi
  done
}

main "$@"
