#!/usr/bin/env bash

set -e

main() {
  if [ "$1" == 'show' ]; then
    defaults write com.apple.finder AppleShowAllFiles YES
  elif [ "$1" == 'hide' ]; then
    defaults write com.apple.finder AppleShowAllFiles NO
  fi
  killall Finder
}
main "$@"
