#!/bin/bash

main() {
  reset-branch
  remove-all-branches-besides-current
  remove-all-stashes
  remove-all-uncheked-files
}

reset-branch() {
  git reset --hard 2>&1 > /dev/null
}

remove-all-branches-besides-current() {
  git branch -D $(git branch | grep -v \* | xargs) 2>&1 > /dev/null | true
}

remove-all-stashes() {
  git stash clear
}

remove-all-uncheked-files() {
  git clean -d -f
}

main
