#!/usr/bin/env ruby
require 'fileutils'
require 'erb'
require 'ostruct'
require 'json'

require 'pry'

def main
  throw 'Please provide DOTFILES_PATH' unless ENV['DOTFILES_PATH']
  dotfiles_path = ENV['DOTFILES_PATH']

  require "#{dotfiles_path}/lib/dotfiles_processor"
  require "#{dotfiles_path}/lib/dotfiles_installer"
  require "#{dotfiles_path}/lib/karabiner_configurer"
  require "#{dotfiles_path}/lib/pomodoremi_installer"
  require "#{dotfiles_path}/lib/scripts_installer"

  private = JSON.parse File.read "#{dotfiles_path}/configuration/env/private.json"
  public = JSON.parse File.read "#{dotfiles_path}/configuration/env/public.json"

  config_hash = {}
  private.merge(public).each do |k,v|
    config_hash[k.downcase] = v
  end

  $config = OpenStruct.new(config_hash)

  Dir.chdir dotfiles_path

  DotfilesInstaller.exec
  KarabinerConfigurer.exec
  PomodoremiInstaller.exec
  ScriptsInstaller.exec
end

main
