#!/bin/bash

if test -z "$BASH_VERSION"; then
  echo "Please run this script using bash, not sh or any other shell." >&2
  exit 1
fi

main() {
  set -euo pipefail

  if [ ! -f private.json ]; then
    echo "Please provide private.json"
  fi

  DOTFILES_PATH="$(extract-dotfiles-path)"
  DOTFILES_REPO="$(extract-dotfiles-repo)"
  mkdir -p "$DOTFILES_PATH"
  # install-strap
  git clone "$DOTFILES_REPO" "$DOTFILES_PATH"
  mv private.json "$DOTFILES_PATH/configuration/env/private.json"
}

install-strap() {
  # mk tmp file
  curl https://raw.githubusercontent.com/MikeMcQuaid/strap/master/bin/strap.sh > strap.sh
  chmod +x strap.sh
  ./strap.sh
}
extract-dotfiles-path() {
    cat private.json |
        grep \"DOTFILES_PATH\": |
        sed 's/.*"DOTFILES_PATH": *"//' |
        sed 's/".*//'
}

extract-dotfiles-repo() {
    cat private.json |
        grep \"DOTFILES_REPO\": |
        sed 's/.*"DOTFILES_REPO": *"//' |
        sed 's/".*//'
}

main
