#!/usr/bin/env ruby
require 'fileutils'
require 'erb'
require 'ostruct'
require 'json'

require 'pry'

def main
  throw 'Please provide DOTFILES_DIR' unless ENV['DOTFILES_DIR']
  dotfiles_dir = ENV['DOTFILES_DIR']

  require "#{dotfiles_dir}/lib/dotfiles_processor"
  require "#{dotfiles_dir}/lib/dotfiles_installer"
  require "#{dotfiles_dir}/lib/karabiner_configurer"
  require "#{dotfiles_dir}/lib/pomodoremi_installer"
  require "#{dotfiles_dir}/lib/scripts_installer"

  private = JSON.parse File.read "#{dotfiles_dir}/configuration/env/private.json"
  public = JSON.parse File.read "#{dotfiles_dir}/configuration/env/public.json"

  config_hash = {}
  private.merge(public).each do |k,v|
    config_hash[k.downcase] = v
  end

  $config = OpenStruct.new(config_hash)

  Dir.chdir dotfiles_dir

  DotfilesInstaller.exec
  KarabinerConfigurer.exec
  PomodoremiInstaller.exec
  ScriptsInstaller.exec
end

main
