#!/usr/bin/env bash

set -e
main() {
  files_found="$(find-files)"
  if [[ $files_found ]]; then
    echo "There were some staged changes found with debug info"
    echo "You can add files to .nodebugignore if you want yet to proceed with commit"
    echo
    echo "$files_found"
    exit 1
  else
    exit 0
  fi
}

get-match() {
  focus=(
    '@focus'
    'console.log('
    'debugger;'
    'describe.only'
    'it.only'
    'focus: true'
    ':focus'
  )

  echo "\($(join '\)\|\(' "${focus[@]}")\)"
}

staged-additions() {
  git diff --staged "$1" | grep '^\+' | grep -v '^\+\{3\}'
}

has-focus() {
  grep -q "$(get-match)"
}

find-files() {
  git diff --staged --name-only | ignore-whitelisted | while read -r file; do
    if staged-additions "$file" | has-focus; then
      echo "$file"
    fi
  done
}

ignore-whitelisted() {
  while read -r line; do
    if ! ([ -e './.nodebugignore' ] && match-whitelisted "$line"); then
      echo "$line"
    fi
  done
}

match-whitelisted() {
  found=''
  while read -r pattern; do
    if [[ "$1" == $pattern ]]; then
      found='true'
      break
    fi
  done < './.nodebugignore'

  if [ -n "$found" ]; then
    return 0
  else
    return 1
  fi
}

join() {
  # http://stackoverflow.com/a/17841619/319918
  local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}";
}
main "$@"
