#!/usr/bin/env bash

set -e
main() {
  files_found="$(find-files)"
  if [[ $files_found ]]; then
    echo "There were some files found with debug info"
    echo "You can add them to .nodebugignore if you want yet to proceed with commit"
    echo "$files_found" | while read -r file; do
      git grep "$(get-match)" "$file" | cat
    done
    exit 1
  else
    exit 0
  fi
}

get-match() {
  focus=(
    '@focus'
    'console.log('
    'debugger;'
    'describe.only'
    'it.only'
    'focus: true'
    ':focus'
  )

  echo "\($(join '\)\|\(' "${focus[@]}")\)"
}

find-files() {
  git grep -l "$(get-match)" | ignore-whitelisted
}

ignore-whitelisted() {
  while read -r line; do
    if ! ([ -e './.nodebugignore' ] && match-whitelisted "$line"); then
      echo "$line"
    fi
  done
}

match-whitelisted() {
  found=''
  while read -r pattern; do
    if [[ "$1" == $pattern ]]; then
      found='true'
      break
    fi
  done < './.nodebugignore'

  if [ -n "$found" ]; then
    return 0
  else
    return 1
  fi
}

join() {
  # http://stackoverflow.com/a/17841619/319918
  local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}";
}
main "$@"
