#!/usr/bin/env bash

set -e

main() {
  # /opt/boxen/homebrew/bin/terminal-notifier -message '!!oo'
  # env
  enforce-heartbeat
}

enforce-heartbeat() {
  HEARTBEAT_FILE="$HOME/main/support/temp/dotfiles/heartbeat"
  ICON="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ToolbarFavoritesIcon.icns"
  DAY_IN_SECONDS=86400
  last_heartbeat_time="$(stat -f "%m" "$HEARTBEAT_FILE")"
  current_time="$(date +%s)"
  time_passed=$(( (current_time - last_heartbeat_time) ))
  if [ $time_passed -gt $DAY_IN_SECONDS ]; then
    terminal-notifier -message 'HEARTBEAT' -appIcon "$ICON"
  fi
}

main "$@"
