#!/usr/bin/env bash

set -e

main() {
  sudo -v
  case "$1" in
    count | help | list | update)
    ;;
    *)
      echo "ERROR: unknown action \"$1\""
      exit 1
      ;;
  esac

  if [ "$2" == '--no-fetch' ] || [ "$3" == '--no-fetch' ]; then
    no_fetch='--no-fetch'
  fi

  if [ "$2" != '--no-fetch' ]; then
    updater_to_use="updater-$2"
  fi

  updaters | while read -r updater; do
    source "$updater"

    updater_handle="$(basename "$updater")"

    if "$updater_handle-detect" &&
        ([ "$updater_handle" == "$updater_to_use" ] ||
         [ -z "$updater_to_use" ]) ; then
      echo "$("$updater_handle-name"):"

      case "$1" in
        count)
          "$updater_handle-count" "$no_fetch"
          ;;
        list)
          "$updater_handle-list" "$no_fetch"
          ;;
        update)
          "$updater_handle-update"
          ;;
      esac
      echo ""
    fi
  done
}

updaters() {
  find "$UPDATER_PATH" -iname "updater-*"
}


main "$@"
