#!/usr/bin/env bash

set -e

main() {
  case "$1" in
    restore)
      restore
      ;;
    *)
      backup
      ;;
  esac
}


backup() {
  echo Backing up...
  backup-one 'Alpha'
  backup-one 'Iota'
  backup-one 'Lambda'
  backup-one 'Mu'
  backup-one 'Omicron'
  backup-one 'Psy'
  backup-one 'Omega'
}

restore() {
  echo Restoring...
  restore-one 'Alpha'
  restore-one 'Iota'
  restore-one 'Lambda'
  restore-one 'Mu'
  restore-one 'Omicron'
  restore-one 'Psy'
  restore-one 'Omega'

}

backup-one() {
  echo "backing up $1"
  rclone sync -v --filter-from "$HOME/.rclone_products_filter" \
    "$HOME/main/$1" \
    "backblaze_b2:w97-backup/$1"
}

restore-one() {
  echo "restoring $1"
  rclone sync -v --filter-from "$HOME/.rclone_products_filter" \
    "backblaze_b2:w97-backup/$1" \
    "$HOME/main/$1"
}

main "$@"
