#!/bin/bash

# Utils
# ==============================================================================

# Main
# ==============================================================================

main() {
  export NVM_DIR="$HOME/.nvm"
  # shellcheck disable=SC1090
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
}

main "$@"
