#!/usr/bin/env bash

set -e

main() {
  cd "$DOTFILES_BIN_REPO/apps" || exit
  for file in *.app.zip; do
    appname="$(basename "$file" .zip)"
    if [ ! -e "/Applications/$appname" ]; then
      unzip "$DOTFILES_BIN_REPO/apps/$appname.zip" > /dev/null &&
      mv "$DOTFILES_BIN_REPO/apps/$appname" "/Applications/$appname"
      echo "install-private-apps: $appname"
    fi
  done;
}

main "$@"
