#!/usr/bin/env bash

set -e

main() {
  echo "Configuring OSX"

  # Normal scrolling direction
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
  # Reenable notifications
  launchctl load -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist

  # Dark mode
  dark-mode --mode Dark

  # Black background
  set-black-wallpaper

  # Light blue highlight (like in Iterm)
  defaults write NSGlobalDomain AppleHighlightColor -string "0.71 0.84 1"

  # Hide all icons from desktop
  defaults write com.apple.finder CreateDesktop -bool false

  set-up-finder

  killall Finder
}
set-up-finder() {
  defaults write com.apple.finder ShowStatusBar -bool false
  defaults write com.apple.finder ShowPathbar -bool false

  defaults write com.apple.finder NewWindowTarget -string "PfLo"
  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/main/"
}

set-black-wallpaper() {
  if [ ! "$(wallpaper)" = "$HOME/.wallpaper.png" ]; then
    generate-image black "$HOME/.wallpaper.png"
    osx-app-spaces-manager --each-space="wallpaper '$HOME/.wallpaper.png'"
  fi
}

generate-image() {
  convert -size 100x100 xc:"$1" "$2"
}

main "$@"
