#!/usr/bin/env bash

set -e

main() {
  echo "Configuring OSX"

  # Normal scrolling direction
  defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
  # Reenable notifications
  launchctl load -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist

  # Dark mode
  dark-mode --mode Dark

  # Black background
  set-black-wallpaper

  # Black highlight
  defaults write NSGlobalDomain AppleHighlightColor -string "0 0 0"

  # Hide all icons from desktop
  defaults write com.apple.finder CreateDesktop -bool false

  killall Finder
}

set-black-wallpaper() {
  if [ ! "$(wallpaper)" = "$HOME/.wallpaper.png" ]; then
    generate-image black "$HOME/.wallpaper.png"
    osx-app-spaces-manager --each-space="wallpaper '$HOME/.wallpaper.png'"
  fi
}

generate-image() {
  convert -size 100x100 xc:"$1" "$2"
}

main "$@"
