#!/bin/bash

# Utils
# ==============================================================================

configureFirefoxContainers() {
  print_check "Configuring Firefox Containers"
  print_block_start

  mv "$TEMP_BUILD_PATH/browsers_dotfiles/containers.json" "$TEMP_BUILD_PATH/browsers_dotfiles/containers.json.backup" || true

  node "$BUNDLES_PATH/$1/firefoxContainers"

  if ! diff "$TEMP_BUILD_PATH/browsers_dotfiles/containers.json" "$TEMP_BUILD_PATH /browsers_dotfiles/containers.json.backup" >/dev/null 2>&1; then

    echo "Firefox will restart now"
    echo "Close it, if it won't do so automatically"
    osascript -e 'tell application "Firefox" to quit'
    read -rp "Press any key to continue"
    open -a Firefox

  fi
  print_block_end
}

configureFirefoxContainerise() {
  print_check "Configuring Firefox Containerise"

  mv "$TEMP_BUILD_PATH/browsers_dotfiles/containerise.csv" "$TEMP_BUILD_PATH/browsers_dotfiles/containerise.csv.backup" || true

  node "$BUNDLES_PATH/$1/firefoxContainerise"

  if diff "$TEMP_BUILD_PATH/browsers_dotfiles/containerise.csv" "$TEMP_BUILD_PATH/browsers_dotfiles/containerise.csv.backup" >/dev/null 2>&1; then
    print_success "skip"
  else
    print_block_start

    pbcopy < "$TEMP_BUILD_PATH/browsers_dotfiles/containerise.csv"
    echo "Containerise config was copied to the clipboard"
    echo "Paste it to your extension"
    echo ""
    read -rp "Press any key to continue"

    print_block_end
  fi
}

configureFirefoxBlockSite() {
  print_check "Configuring Firefox Block Site"

  mv "$TEMP_BUILD_PATH/browsers_dotfiles/block-site-preferences.json" "$TEMP_BUILD_PATH/browsers_dotfiles/block-site-preferences.json.backup" || true

  node "$BUNDLES_PATH/$1/firefoxBlockSite"

  if diff "$TEMP_BUILD_PATH/browsers_dotfiles/block-site-preferences.json" "$TEMP_BUILD_PATH/browsers_dotfiles/block-site-preferences.json.backup" >/dev/null 2>&1; then
    print_success "skip"
  else
    print_block_start

    cp "$TEMP_BUILD_PATH/browsers_dotfiles/block-site-preferences.json" "$FINAL_HOME_PATH/Documents/block-site-preferences.json"
    echo "Block Site config was copied to ~/Documents/block-site-preferences.json"
    echo "Import it into your extension"
    echo ""
    read -rp "Press any key to continue"

    rm "$FINAL_HOME_PATH/Documents/block-site-preferences.json"
    print_block_end
  fi
}

configureFinicky() {
  print_check "Configuring Finicky"
  print_block_start

  mv "$TEMP_BUILD_PATH/browsers_dotfiles/.finicky.js" "$TEMP_BUILD_PATH/browsers_dotfiles/.finicky.js.backup" || true

  node "$BUNDLES_PATH/$1/finicky"

  print_block_end

}


_listRedirectors() {
  find "$TEMP_BUILD_PATH/browsers_dotfiles/redirectors" -iname "*.json" \
  || true
}

configureRedirectors() {
  print_check "Configuring Redirectors"
  print_block_start


  (_listRedirectors) | while read -r file; do
    mv "$file" "${file}.backup" || true
  done


  node "$BUNDLES_PATH/$1/redirectors"

  find "$TEMP_BUILD_PATH/browsers_dotfiles/redirectors" -iname "*.json" || true

  (_listRedirectors) | while read -r file; do
    if ! diff "$file" "${file}.backup" >/dev/null 2>&1; then
      filename="$(basename "$file")"
      cp "$file" "$FINAL_HOME_PATH/Documents/${filename}"

      echo "Redirectors config for $(basename "$filename" .json) was copied to ~/Documents/${filename}"

      echo "Import it into your extension"
      echo ""
      read -rp "Press any key to continue" < /dev/tty

      rm "$FINAL_HOME_PATH/Documents/${filename}"
    fi

  done


  print_block_end

}


# Main
# ==============================================================================

main() {
  configureFirefoxContainers "$1"
  configureFirefoxContainerise "$1"
  #configureFirefoxBlockSite "$1"
  configureFinicky "$1"
  configureRedirectors "$1"
}

main "$@"
