#!/bin/bash

# Utils
# ==============================================================================

switch_space() {
  keys=(\
    h t n s \
    h t n s \
    g c r l \
    g c r l \
  )


  modifiers=(\
    control control control control \
    option option option option \
    control control control control \
    option option option option
  )

  key="${keys[$1]}"
  modifier="${modifiers[$1]}"

  osascript -s s -l JavaScript -e "\
      systemEvents = Application('System Events');\
      systemEvents.keystroke('$key', { using: ['command down', '$modifier down'] } );\
      "
  sleep 2
}

generate_color_image() {
  convert -size 800x800 xc:"$1" "$2"
}

# Main
# ==============================================================================

main() {
  print_check "Setting up wallpapers"
  if [[ -f "$BUILD_PATH/temp/osx_more/0.png" ]]; then
    print_success
    return
  fi
  return
  colors=(
    '#fea57c' '#f2c500' '#0dd677' '#00b7ff' \
    '#953506' '#765d05' '#0d6135' '#124b68' \
    '#fea57c' '#f2c500' '#0dd677' '#00b7ff' \
    '#953506' '#765d05' '#0d6135' '#124b68'
  )
  mkdir -p "$BUILD_PATH/temp/osx_more"
  for i in $(seq 0 15); do
    generate_color_image "${colors[$i]}" "$BUILD_PATH/temp/osx_more/$i.png"
    switch_space "$i"
    wallpaper set "$BUILD_PATH/temp/osx_more/$i.png"
    sleep 1
  done

  print_success
}

main "$@"
