#!/bin/bash

# Utils
# ==============================================================================

STRAP_URL="https://github.com/MikeMcQuaid/strap"
STRAP_SOURCE_URL="https://raw.githubusercontent.com/MikeMcQuaid/strap/master/bin/strap.sh"

strap_source_found() {
  curl -fs "$STRAP_SOURCE_URL" > /dev/null 2>&1
}

install_strap() {
  print_check "Strap is installed"
  if command -v brew  > /dev/null 2>&1; then
    print_success 'Brew found, so strap is likely installed'
  else
    print_block_start
    printf -- '- Is strap repository still relevant?\n'
    printf "  URL: %s\n\n" "${STRAP_URL}"

    confirm
    if ! strap_source_found; then
      throw_error "Strap not found"
    fi

    bash <(curl -fs "$STRAP_SOURCE_URL")

    print_block_end
  fi
}

# Main
# ==============================================================================

main() {
  install_strap
}

main "$@"
