#!/bin/bash

# Utils
# ==============================================================================

# Main
# ==============================================================================

main() {
  # TODO: Remove this
  return
  RCLONE_CONFIG_PASS="$(battlecruiser_get_config rclone_config_pass)"
  export RCLONE_CONFIG_PASS
}

main "$@"
