#!/bin/bash

if test -z "$BASH_VERSION"; then
  echo "Please run this script using bash, not sh or any other shell." >&2
  exit 1
fi

main() {
  set -euo pipefail

  if ! is-dotfiles-installed && [ ! -f private.json ]; then
    echo 'Please provide private.json'
    exit
  fi

  install-strap

  if is-dotfiles-installed; then
    configure-machine
  else
    DOTFILES_PATH="$(extract-dotfiles-path)"
    export DOTFILES_PATH
    setup-dotfiles
    configure-machine
  fi
}

install-strap() {
  FILE="$(mktemp "$TMPDIR"strap.XXXXXXXXXX).sh"
  curl https://raw.githubusercontent.com/MikeMcQuaid/strap/master/bin/strap.sh > $FILE
  chmod +x "$FILE"
  "$FILE"
}

setup-dotfiles() {
  DOTFILES_REPO="$(extract-dotfiles-repo)"

  mkdir -p "$DOTFILES_PATH"
  git clone "$DOTFILES_REPO" "$DOTFILES_PATH"
  mv private.json "$DOTFILES_PATH/configuration/env/private.json"
}

configure-machine() {
  "$DOTFILES_PATH/scripts/configure-machine"
}

is-dotfiles-installed() {
  [ ! -z "${DOTFILES_PATH-}" ] && [ -e "$DOTFILES_PATH/.git" ]
}

extract-dotfiles-path() {
  cat private.json |
    grep \"DOTFILES_PATH\": |
    sed 's/.*"DOTFILES_PATH": *"//' |
    sed 's/".*//'
}

extract-dotfiles-repo() {
  cat private.json |
    grep \"DOTFILES_REPO\": |
    sed 's/.*"DOTFILES_REPO": *"//' |
    sed 's/".*//'
}

main
