#!/usr/bin/env bash

set -e

main() {
  new_mac="$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/./0/2; s/.$//')"
  sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z
  sudo ifconfig en0 ether "$new_mac"
  networksetup -detectnewhardware
}

main "$@"
