#!/usr/bin/env ruby
require 'project_config'
require 'mini_magick'

setup_project_config :dotfiles

module IphoneSync
  def self.import_documents
    documents = Dir.new("#{ProjectConfig.iphone_path}/photos/documents")
    documents_source = Dir.new(ProjectConfig.documents_path)

    FileUtils.rm_rf documents
    FileUtils.mkdir_p documents

    Dir["#{documents_source.path}/**/*"]
      .select { |f| /(jpg|png|pdf)\Z/i =~ f }.each do |file|
      if /pdf\Z/ =~ file
        destination = "#{documents.path}/#{File.basename file, '.pdf'}.png"
        `sips -s format png --out #{destination} #{file}`
      else
        FileUtils.cp file, documents.path
      end
    end
  end

  def self.import_books
    iphone_books =  Dir.new("#{ProjectConfig.iphone_path}/books")
    importer = Dir.new("#{ProjectConfig.itunes_path}/Automatically Add to iTunes.localized")

    iphone_books.entries
      .reject {|f| /^\./ =~ f}
      .each { |b| FileUtils.cp "#{iphone_books.path}/#{b}", importer.path}
  end
end

case ARGV[0]
when 'documents'
  IphoneSync.import_documents
when 'books'
  IphoneSync.import_books
end
