#!/bin/bash

# Main
# ==============================================================================

use_zoxide() {
  eval "$(zoxide init zsh)"
}

main() {
  use_zoxide
}

main "$@"


c() {
  local previous=$PWD
  if [ "$#" -eq 0 ]; then
    cd -
  elif [ -d "$*" ]; then
    cd "$*"
  elif [ -f "$*" ]; then
    cd "$(dirname "$*")"
    local file="$(basename "$*")"
  else
    z "$*"
  fi

  if [ "$PWD" != "$previous" ]; then
    if [ ! -z "$file" ]; then
      echo "$(script -q /dev/null ls -aG . | highlight "$file" | cat)"
    else
      ls -a
    fi
  fi
}
