#!/bin/bash

# Utils
# ==============================================================================

configure_iterm2() {
  print_check "iTerm2 configuration"
  # Don’t display the annoying prompt when quitting iTerm
  defaults write com.googlecode.iterm2 PromptOnQuit -bool false
  print_success
}

# Main
# ==============================================================================

main() {
  configure_iterm2
}

main "$@"
